import { ProductQueryResult, ProductQueryResultDbMock } from '../models/product.models';

/*
  SQL that helps to prepare DB mock:

    SELECT
      "QWERTY", p.externalId, p.name, CONCAT(m.name, ' UIOP'), "tags"
    FROM
      product as p
      LEFT JOIN
        manufacturer as m ON p.manufacturerId = m.id
    WHERE
      p.type = 'Product'
 */

const productQueryResultDbMocks: ProductQueryResultDbMock[] = [
  [1, 'Owoc aronii 50g', 'Flos', null],
  [2, 'Korzeń arcydzięgla 50g', 'Flos', null],
  [3, 'Kwiat akacji 50g', 'Flos', null],
  [4, 'Owoc berberysu 50g', 'Flos', null],
  [5, 'Owoc borówki czernicy - herbatka ziołowa 50g', 'Flos', null],
  [6, 'Bylica boże drzewko 50g', 'Flos', null],
  [7, 'Ziele cykorii 50g', 'Flos', null],
  [8, 'Ziele dymnicy 50g', 'Flos', null],
  [9, 'Owoc jarzębiny 50g', 'Flos', null],
  [10, 'Kwiat jasnoty 25g', 'Flos', null],
  [11, 'Ziele jeżówki purpurowej 50g', 'Flos', null],
  [12, 'Kora kaliny koralowej 50g', 'Flos', null],
  [13, 'Kora kasztanowca 50g', 'Flos', null],
  [14, 'Owoc kopru włoskiego 50g', 'Flos', null],
  [15, 'Liść karczocha 50g', 'Flos', null],
  [16, 'Korzeń kobylaka 50g', 'Flos', null],
  [17, 'Kwiat czerwonej koniczyny 50g', 'Flos', null],
  [18, 'Kwiatostan lipy 50g', 'Flos', null],
  [19, 'Korzeń łopaniu 50g', 'Flos', null],
  [20, 'Ziele macierzanki 50g', 'Flos', null],
  [21, 'Liść maliny 50g', 'Flos', null],
  [22, 'Ziele marzanki wonnej 50g', 'Flos', null],
  [23, 'Liść melisy 50g', 'Flos', null],
  [24, 'Liść mięty 50g', 'Flos', null],
  [25, 'Korzeń mniszka 50g', 'Flos', null],
  [26, 'Morszczyn 50g', 'Flos', null],
  [27, 'Kwiat czarnej malwy 50g', 'Flos', null],
  [28, 'Kwiat nagietka 50g', 'Flos', null],
  [29, 'Owoc niepokalanka mielony 100g', 'Flos', null],
  [30, 'Ziele nostrzyka 50g', 'Flos', null],
  [31, 'Owoc ostropestu mielony odtłuszczony 100g', 'Flos', null],
  [32, 'Owoc ostropestu plamistego 100g', 'Flos', null],
  [33, 'Korzeń omanu 50g', 'Flos', null],
  [34, 'Kwiat pierwiosnka 50g', 'Dary Natury', null],
  [35, 'Ziele przytulii właściwej 50g', 'Flos', null],
  [36, 'Liść podagrycznika 50g', 'Flos', null],
  [37, 'Ziele połonicznika 50g', 'Flos', null],
  [38, 'Liść poziomki 50g', 'Flos', null],
  [39, 'Liść prawoślazu 50g', 'Flos', null],
  [40, 'Owoc róży 50g', 'Flos', null],
  [41, 'Koszyczek rumianku 50g', 'Flos', null],
  [42, 'Ziele rutwicy 50g', 'Flos', null],
  [43, 'Siemię lniane 250g', 'Flos', null],
  [44, 'Ziele skrzypu 50g', 'Flos', null],
  [45, 'Kwiat słonecznika 50g', 'Flos', null],
  [46, 'Kwiat stokrotki 25g', 'Flos', null],
  [47, 'Ziele szanty 50g', 'Flos', null],
  [48, 'Liść szałwii 50g', 'Flos', null],
  [49, 'Korzeń szczeci 50g', 'Flos', null],
  [50, 'Ziele szczeci 50g', 'Flos', null],
  [51, 'Ziele wierzbownicy drobnokwiatowej 50g', 'Flos', null],
  [52, 'Kłącze wężownika 50g', 'Flos', null],
  [53, 'Liść werbeny cytrynowej 50g', 'Flos', null],
  [54, 'Wilkakora 50g', 'Flos', null],
  [55, 'Kwiat wrzosu 50g', 'Flos', null],
  [56, 'Korzeń żywokostu 50g', 'Flos', null],
  [57, 'Liść melisy - herbatka ziołowa 30x1,5g', 'Flos', null],
  [58, 'Liść mięty - herbatka ziołowa 30x1,5g', 'Flos', null],
  [59, 'Owoc głogu - herbatka owocowa w saszetkach 25x2g', 'Flos', null],
  [60, 'Ziele wierzbownicy drobnokwiatowej 25x2g', 'Flos', null],
  [61, 'Witamina D3 (4000IU) + K2mk7 Forte - krople (30ml)', 'Aura Herbals', null],
  [62, 'Oryginalne mydło Aleppo oliwkowe 200g', 'Zhenobya', null],
  [63, 'Oryginalne mydło z Aleppo 12% oleju laurowego 200g', 'Zhenobya', null],
  [64, 'Oryginalne mydło z Aleppo 25% oleju laurowego 200g', 'Zhenobya', null],
  [65, 'Mydło dziegciowe twarde 140g', 'Bioarp', null],
  [66, 'Bursztyn bałtycki na nalewkę 50g', 'Dobrynin', null],
  [67, 'Ekologiczny ocet jabłkowy 750ml', 'Voelkel', null],
  [68, 'Złoto z rokitnika - niepasteryzowany mus z owoców rokitnika 500ml', 'Rokitnik i przyjaciele Sp. z o.o.', null],
  [69, 'Maść żywokostowa 150ml', 'Farm-vix', null],
  [70, 'Maść z żyworódki 150ml', 'Farm-vix', null],
  [71, 'Maść z omułka zielonowargowego 150ml', 'Farm-vix', null],
  [72, 'Maść na popękane pięty 150ml', 'Farm-vix', null],
  [73, 'Maść borowinowa 150ml', 'Farm-vix', null],
  [74, 'Maść z żyworódki i konopi 150ml', 'Farm-vix', null],
  [75, 'Maść kasztanowa z rutyną 150ml', 'Farm-vix', null],
  [76, 'Balsam krzemowy prof. Tuszyńskiego 200 ml', 'Limba', null],
  [77, 'Mydełko antybakteryjne z oregano 80g', 'MarokoProdukt', null],
  [78, 'Naturalne mydło z siarką i piołunem 100g', 'Mydlarnia „Powrót do Natury”', null],
  [79, 'Naturalne mydło z błotem z morza martwego 100g', 'Mydlarnia „Powrót do Natury”', null],
  [80, 'Mydło geraniowe z zieloną glinką 100g', 'Mydlarnia „Powrót do Natury”', null],
  [81, 'Hipoalergiczne mydło dla niemowląt i dzieci 100g', 'Mydlarnia „Powrót do Natury”', null],
  [82, 'Naturalne mydło z olejem z drzewa herbacianego i oregano 100g', 'Mydlarnia „Powrót do Natury”', null],
  [83, 'Naturalne mydło z wodą utlenioną i złotem monojonowym 100g', 'Mydlarnia „Powrót do Natury”', null],
  [84, 'Naturalne mydło potasowe w płynie 500ml', 'Mydlarnia „Powrót do Natury”', null],
  [85, 'Mydło dla dzieci w płynie 300ml', 'Baby Anthyllis Pierpaoli', null],
  [86, 'Żelowa pasta do zębów dla dzieci bez fluoru 75ml', 'Baby Anthyllis Pierpaoli', null],
  [87, 'Mleczko-krem nawilżający z aloesem i ekstraktem z alg dla dzieci 100ml', 'Baby Anthyllis Pierpaoli', null],
  [88, 'Mgiełka solankowa jodowo-bromowa 950ml', 'Dr Zabłocka', null],
  [89, 'Zabłocka solanka termalna jodowo-bromowa 950ml', 'Dr Zabłocka', null],
  [90, 'Borelyma 30 kapsułek', 'Herbal Pharmaceuticals', null],
  [91, 'Lawenda i różeniec na stres - 30 kapsułek wegetariańskich', 'Herbal Pharmaceuticals', null],
  [92, 'Sinugrip zatoki 15 kapsułek', 'Herbal Pharmaceuticals', null],
  [93, 'Mirra i propolis na gardło - 12 pastylek do ssania', 'Herbal Pharmaceuticals', null],
  [94, 'Laxi cortex - 15 kapsułek wegetariańskich', 'Herbal Pharmaceuticals', null],
  [95, 'Orelon NaturSpray 15ml', 'Herbal Pharmaceuticals', null],
  [96, 'Ekologiczny kwiat wiązówki 25g', 'Dary Natury', null],
  [97, 'Ekologiczne ziele glistnika 50g', 'Dary Natury', null],
  [98, 'Ekologiczne ziele przywrotnika 25g', 'Dary Natury', null],
  [99, 'Ziele ruty 50g', 'Dary Natury', null],
  [100, 'Ziele karbieńca 50g', 'Dary Natury', null],
  [101, 'Ekologiczny liść werbeny cytrynowej 25g', 'Dary Natury', null],
  [102, 'Ziele krwiściągu lekarskiego 50g', 'Dary Natury', null],
  [103, 'Ekologiczne pączki sosny 50g', 'Dary Natury', null],
  [104, 'Ekologiczna kora dębu 100g', 'Dary Natury', null],
  [105, 'Ekologiczny kwiat głogu 50g', 'Dary Natury', null],
  [106, 'Ekologiczny korzeń biedrzeńca 25g', 'Dary Natury', null],
  [107, 'Ekologiczny korzeń kobylaka 50g', 'Dary Natury', null],
  [108, 'Ekologiczne ziele ostrożenia 25g', 'Dary Natury', null],
  [109, 'Ekologiczne ziele poziewnika 50g', 'Dary Natury', null],
  [110, 'Ekologiczne ziele rzepiku 50g', 'Dary Natury', null],
  [111, 'Ekologiczny kwiat ślazu 20g', 'Dary Natury', null],
  [112, 'Ekologiczne ziele uczepu 50g', 'Dary Natury', null],
  [113, 'Ekologiczne ziele pięciornika gęsiego 50g', 'Dary Natury', null],
  [114, 'Ekologiczne szyszki chmielu 25g', 'Dary Natury', null],
  [115, 'Ekologiczne ziele owsa 40g', 'Dary Natury', null],
  [116, 'Ekologiczny kwiatostan kocanki 25g', 'Dary Natury', null],
  [117, 'Ekologiczne ziele krwawnika 50g', 'Dary Natury', null],
  [118, 'Ekologiczne ziele dziurawca 50g', 'Dary Natury', null],
  [119, 'Ekologiczne ziele przytulii 50g', 'Dary Natury', null],
  [120, 'Ekologiczne kłącze perzu 50g', 'Dary Natury', null],
  [121, 'Ekologiczny liść babki lancetowatej 25g', 'Dary Natury', null],
  [122, 'Ekologiczne ziele jemioły 50g', 'Dary Natury', null],
  [123, 'Ekologiczny korzeń kozłka lekarskiego 100g', 'Dary Natury', null],
  [124, 'Ekologiczne ziele rdestu ptasiego 50g', 'Dary Natury', null],
  [125, 'Ekologiczne kłącze pięciornika kurze ziele 100g', 'Dary Natury', null],
  [126, 'Ekologiczny korzeń żywokostu 100g', 'Dary Natury', null],
  [127, 'Owoc bzu czarnego 100g', 'Dary Natury', null],
  [128, 'Ekologiczny owoc głogu 100g', 'Dary Natury', null],
  [129, 'Ekologiczny owoc tarniny 100g', 'Dary Natury', null],
  [130, 'Ekologiczna papryka czerwona mielona 50g', 'Dary Natury', null],
  [131, 'Ekologiczny anyż 30g', 'Dary Natury', null],
  [132, 'Ekologiczny imbir 60g', 'Dary Natury', null],
  [133, 'Ekologiczna kolendra mielona 30g', 'Dary Natury', null],
  [134, 'Ekologiczny liść laurowy 10g', 'Dary Natury', null],
  [135, 'Ekologiczna kurkuma mielona 50g', 'Dary Natury', null],
  [136, 'Ekologiczna papryka ostra mielona 90g', 'Dary Natury', null],
  [137, 'Ekologiczna natka pietruszki 20g', 'Dary Natury', null],
  [138, 'Ekologiczny koperek 30g', 'Dary Natury', null],
  [139, 'Ekologiczna trawa cytrynowa 20g', 'Dary Natury', null],
  [140, 'Ekologiczny czosnek mielony 50g', 'Dary Natury', null],
  [141, 'Ekologiczny rozmaryn 30g', 'Dary Natury', null],
  [142, 'Ekologiczna bazylia 25g', 'Dary Natury', null],
  [143, 'Ekologiczny cząber 20g', 'Dary Natury', null],
  [144, 'Ekologiczny lubczyk 20g', 'Dary Natury', null],
  [145, 'Ekologiczny Majeranek 15g', 'Dary Natury', null],
  [146, 'Ekologiczny tymianek 20g', 'Dary Natury', null],
  [147, 'Pieprz czerwony 20g', 'Dary Natury', null],
  [148, 'Pieprz czarny ziarnisty 50g', 'Dary Natury', null],
  [149, 'Gorczyca biała 90g', 'Dary Natury', null],
  [150, 'Ziele angielskie 50g', 'Dary Natury', null],
  [151, 'Jałowiec 30g', 'Dary Natury', null],
  [152, 'Kminek mielony 60g', 'Dary Natury', null],
  [153, 'Pieprz czarny mielony 50g', 'Dary Natury', null],
  [154, 'Pieprz zielony 20g', 'Dary Natury', null],
  [155, 'Pieprz cayenne 60g', 'Dary Natury', null],
  [156, 'Gałka muszkatołowa 30g', 'Dary Natury', null],
  [157, 'Ekologiczny syrop z owoców dzikiej róży 270ml', 'Dary Natury', null],
  [158, 'Ekologiczny syrop z pączków sosny 270ml', 'Dary Natury', null],
  [159, 'Ekologiczny syrop z pigwowca 270ml', 'Dary Natury', null],
  [160, 'Ekologiczny syrop z głogu 270ml', 'Dary Natury', null],
  [161, 'Ekologiczny sok z kiszonej kapusty 3l', 'Dary Natury', null],
  [162, 'Ekologiczny olej z nasion konopi siewnych 100ml', 'Dary Natury', null],
  [163, 'Ekologiczna herbatka dla dziadka 25x2g', 'Dary Natury', null],
  [164, 'Ekologiczna herbatka na dobranoc 25x2g', 'Dary Natury', null],
  [165, 'Ekologiczny olej z wiesiołka 100ml', 'Dary Natury', null],
  [166, 'Ekologiczna herbata dla nerwusów 25x1,5g', 'Dary Natury', null],
  [167, 'Ekologiczna herbatka laktacyjna 25x2g', 'Dary Natury', null],
  [168, 'Ekologiczna herbatka dla żołądkowców 25x2g', 'Dary Natury', null],
  [169, 'Ekologiczny sok z malin 270ml', 'Dary Natury', null],
  [170, 'Ekologiczny sok z jabłek 3l', 'Dary Natury', null],
  [171, 'Ekologiczny sok z buraków 3l', 'Dary Natury', null],
  [172, 'Ekologiczny sok z kiszonych buraków 3l', 'Dary Natury', null],
  [173, 'Ekologiczny olej dla mam 250ml', 'Dary Natury', null],
  [174, 'Ekologiczny olej dla dzieci junior 250ml', 'Dary Natury', null],
  [175, 'Ekologiczna herbatka malinowo-lipowa 25x2,5g', 'Dary Natury', null],
  [176, 'Ekologiczna herbata z dzikiej róży 25x2g', 'Dary Natury', null],
  [177, 'Ekologiczna herbatka Dobry humor 25x2g', 'Dary Natury', null],
  [178, 'Ekologiczna herbatka Body line 25x2g', 'Dary Natury', null],
  [179, 'Ekologiczna czarna herbata korzenna 25x2g', 'Dary Natury', null],
  [180, 'Ekologiczna czarna herbata z wanilią 25x2g', 'Dary Natury', null],
  [181, 'Ekologiczna czarna herbata odkwaszająca 25x2g', 'Dary Natury', null],
  [182, 'Ekologiczna zielona herbata z yerba mate 25x2g', 'Dary Natury', null],
  [183, 'Ekologiczna zielona herbata z pokrzywą 25x2g', 'Dary Natury', null],
  [184, 'Ekologiczna zielona herbata relaksująca 25x2g', 'Dary Natury', null],
  [185, 'Ekologiczna zielona herbata z jeżówką purpurową 25x2g', 'Dary Natury', null],
  [186, 'Ekologiczna herbata dla serduszka 25x2g', 'Dary Natury', null],
  [187, 'Ekologiczna herbatka Bądź optymistą 25x2g', 'Dary Natury', null],
  [188, 'Ekologiczny syrop z truskawki 270ml', 'Dary Natury', null],
  [189, 'Ekologiczna zielona herbata odkwaszająca 15x2g', 'Dary Natury', null],
  [190, 'Ekologiczny kmin rzymski mielony 30g', 'Dary Natury', null],
  [191, 'Ekologiczna kurkuma mielona 200g', 'Dary Natury', null],
  [192, 'Ekologiczna herbata malinowo-imbirowa 25x3g', 'Dary Natury', null],
  [193, 'Ekologiczny 5% ocet jabłkowy 250ml', 'Dary Natury', null],
  [194, 'Zioła do kąpieli przy żylakach i hemoroidach 4x50g', 'Dary Natury', null],
  [195, 'Zioła w saszetkach do higieny intymnej 4x50g', 'Dary Natury', null],
  [196, 'Zioła do kąpieli przy bezsenności 4x50g', 'Dary Natury', null],
  [197, 'Zioła do kąpieli przy reumatyźmie 4x50g', 'Dary Natury', null],
  [198, 'Zioła do kąpieli przy odchudzaniu 4x50g', 'Dary Natury', null],
  [199, 'Kurkuma i pieprz - 60 kapsułek', 'Dary Natury', null],
  [200, 'Guz brzozy (huba brzozowa) 470mg - 60 kapsułek', 'Dary Natury', null],
  [201, 'Ekologiczny sok z brzozy 270 ml', 'Dary Natury', null],
  [202, 'Ekologiczna herbatka dla dzieci krasnoludek 25x2g', 'Dary Natury', null],
  [203, 'Ekologiczny kwiat bzu czarnego 25x2g - herbatka w saszetkach', 'Dary Natury', null],
  [204, 'Ekologiczne ziele dziurawca 25x2g - zioła do zaparzania w saszetkach', 'Dary Natury', null],
  [205, 'Ekologiczna herbatka seniorita 25x2g', 'Dary Natury', null],
  [206, 'Kwiat wrotyczu 50g', 'Dary Natury', null],
  [207, 'Ekologiczna herbata bomba witaminowa 25x3g', 'Dary Natury', null],
  [208, 'Ziele piołunu 50g', 'Dary Natury', null],
  [209, 'Ekologiczny sok z kiszonych ogórków 3l', 'Dary Natury', null],
  [210, 'Ekologiczna herbatka rozgrzewająca 25x2g', 'Dary Natury', null],
  [211, 'Ekologiczna herbatka dla niejadka 25x2g', 'Dary Natury', null],
  [212, 'Ekologiczna herbata dla kobiet w ciąży 25x2g', 'Dary Natury', null],
  [213, 'Kwiat lawendy 50g', 'Dary Natury', null],
  [214, 'Korzeń traganka 500mg - 100 kapsułek', 'Nanga', null],
  [215, 'Ashwagandha 500mg x 60 kapsułek', 'Nanga', null],
  [216, 'Andrographis paniculata 400mg - 100 kapsułek', 'Nanga', null],
  [217, 'Owoc cytryńca chińskiego 50g', 'Nanga', null],
  [218, 'Tulasi liść święta bazylia 50g', 'Nanga', null],
  [219, `Pau d'arco 100g`, 'Nanga', null],
  [220, 'Andrographis paniculata 50g', 'Nanga', null],
  [221, 'Wilkakora 500mg - 100 kapsułek', 'Nanga', null],
  [222, 'Olej lniany BOFLAX® do diety dr Budwig 250ml', 'IWNiRZ', null],
  [223, 'Sok z granata bez cukru 250ml', 'Sam Sok', null],
  [224, 'Sok z jagód bez cukru 250ml', 'Sam Sok', null],
  [225, 'Sok z jeżyn bez cukru 250ml', 'Viands', null],
  [226, 'Ekologiczny sok z pokrzywy 500ml', 'PolBioEco', null],
  [227, 'Sok z żurawin wielkoowocowych bez cukru 250ml', 'Sam Sok', null],
  [228, 'Sok z żurawin wielkoowocowych bez cukru 500ml', 'Sam Sok', null],
  [229, 'Trawa cytrynowa 50g', 'Merre', null],
  [230, 'Owocowa witamina C - sok z dzikiej róży 250ml', 'Polska Róża', null],
  [231, 'Naturalna woda lecznicza Jan 5l', 'Uzdrowisko Krynica-Żegiestów', null],
  [232, 'Maść tygrysia 3,5g', 'Aura Herbals', null],
  [233, 'Pneumovit baby spray do nosa 35ml', 'Gorvita', null],
  [234, 'Pneumovit sept aerozol do gardła 35ml', 'Gorvita', null],
  [235, 'Pneumovit zatoki spray do nosa 50ml', 'Gorvita', null],
  [236, 'Gumowe bańki akupunkturowe Jianshenguan - 4 sztuki', 'Meridian', null],
  [237, 'Napój panax ginseng extractum 10x10ml (Żeń-szeń)', 'Meridian', null],
  [238, 'Parasine plus 100 kapsułek', 'Mitra', null],
  [239, 'Pasta do zębów dla dzieci bez fluoru 50ml', 'Neobio', null],
  [240, 'Bishovit żel 150ml', 'Remedium Natura', null],
  [241, 'Maść tygrysia rozgrzewająca 100ml', 'Remedium Natura', null],
  [242, 'Maść tygrysia z szungitem 100ml', 'Remedium Natura', null],
  [243, 'Natur C active 100 tabletek', 'Sanbios', null],
  [244, 'Kwiat dziewanny 50g', 'Herbapol Kraków', null],
  [245, 'Ziele świetlika w saszetkach 20x1,5g', 'Herbapol Kraków', null],
  [246, 'Ziele bratka 20x1,5g - herbatka ziołowa w saszetkach', 'Herbapol Kraków', null],
  [247, 'Liść mącznicy lekarskiej 20x1,5g - herbatka ziołowa w saszetkach', 'Herbapol Kraków', null],
  [248, 'Jeżówka purpurowa 20x2g - herbatka ziołowa w saszetkach', 'Herbapol Kraków', null],
  [249, 'Malina z dziewanną 20x2g - herbatka owocowo-ziołowa w saszetkach', 'Herbapol Kraków', null],
  [250, 'Owoc jałowca 50g', 'Herbapol Kraków', null],
  [251, 'Kminek 50g', 'Herbapol Kraków', null],
  [252, 'Liść borówki brusznicy 50g', 'Herbapol Kraków', null],
  [253, 'Korzeń lubczyku 50g', 'Herbapol Kraków', null],
  [254, 'Nasiona kozieradki 50g', 'Herbapol Kraków', null],
  [255, 'Liść orzecha włoskiego 50g', 'Herbapol Kraków', null],
  [256, 'Owoc anyżu 50g', 'Herbapol Kraków', null],
  [257, 'Porost islandzki 50g', 'Herbapol Kraków', null],
  [258, 'Korzeń prawoślazu 50g', 'Herbapol Kraków', null],
  [259, 'Strąki fasoli naowocnia 50g', 'Herbapol Kraków', null],
  [260, 'Syrop pneumopol 100ml', 'Herbapol Kraków', null],
  [261, 'Syrop prawoślazowy 100ml', 'Herbapol Kraków', null],
  [262, 'Syrop sosnowy 100ml', 'Herbapol Kraków', null],
  [263, 'Syrop tymianek i podbiał 100ml', 'Herbapol Kraków', null],
  [264, 'Syrop z dziewanny 100ml', 'Herbapol Kraków', null],
  [265, 'Syrop z porostu islandzkiego i kwiatów bzu 100ml', 'Herbapol Kraków', null],
  [266, 'Tarczyca bajkalska 50g', 'Herbapol Kraków', null],
  [267, 'Ziele tasznika 50g', 'Herbapol Kraków', null],
  [268, 'Ziele świetlika 50g', 'Herbapol Kraków', null],
  [269, 'Reumobonisol płyn do masażu 100g', 'Bonimed', null],
  [270, 'Ziołowy balsam kręgowy Ojca Grzegorza 100g', 'Bonimed', null],
  [271, 'Cardiobonisan Ojca Grzegorza 25x4g - zioła do zaparzania w saszetkach', 'Bonimed', null],
  [272, 'Gastrobonisan Ojca Grzegorza 25x4g - zioła do zaparzania w saszetkach', 'Bonimed', null],
  [273, 'Nefroboniasan Ojca Grzegorza 25x4g - zioła do zaparzania w saszetkach', 'Bonimed', null],
  [274, 'Nerwobonisan Ojca Grzegorza 25x4g - zioła do zaparzania w saszetkach', 'Bonimed', null],
  [275, 'Pulmobonisan Ojca Grzegorza 25x4g - zioła do zaparzania w saszetkach', 'Bonimed', null],
  [276, 'Anginbon aerozol doustny 9ml', 'Bonimed', null],
  [277, 'Resveratrol - esencja wina w kroplach 20ml', 'Bonimed', null],
  [278, 'Balsam jerozolimski dla dzieci 200ml', 'Boni Fratres', null],
  [279, 'Balsam jerozolimski forte 200ml', 'Boni Fratres', null],
  [280, 'Balsam jerozolimski na gardło - 16 pastylek', 'Boni Fratres', null],
  [281, 'Cholestrofratin forte do zaparzania w saszetkach 30x2g', 'Boni Fratres', null],
  [282, 'Diabetofratin forte do zaparzania w saszetkach 30x2g', 'Boni Fratres', null],
  [283, 'Hepatofratin forte do zaparzania w saszetkach 30x2g', 'Boni Fratres', null],
  [284, 'Prostafratin forte do zaparzania w saszetkach 30x2g', 'Boni Fratres', null],
  [285, 'Senfratin forte do zaparzania w saszetkach 30x2g', 'Boni Fratres', null],
  [286, 'Slimfratin forte do zaparzania w saszetkach 30x2g', 'Boni Fratres', null],
  [287, 'Herbatka uodparniająca 100g', 'Boni Fratres', null],
  [293, 'Witamina D3 2000 j.m. 120 kapsułek', 'MedicaLine', null],
  [294, 'Witamina D3 4000 j.m. Forte 120 kapsułek', 'MedicaLine', null],
  [295, 'Witamina K2 MK-7 100 µg z Natto + D3 60 kapsułek', 'MedicaLine', null],
  [296, 'Witamina B complex B-50, 100 VEGE kaps.', 'MedicaLine', null],
  [297, 'Magnez Chelatowany + Witamina B6, 100 kaps.', 'MedicaLine', null],
  [298, 'Taurynian Magnezu z Witaminą B6, 100 vege kaps.', 'Aliness', null],
  [299, 'Cynk Chelatowany 15 mg, 100 tabletek', 'MedicaLine', null],
  [300, 'Selen Select® L-selenometionina 200µg, 100 tabletek', 'MedicaLine', null],
  [301, 'Selen selenian (IV) sodu 100µg, 100 tabletek VEGE', 'MedicaLine', null],
  [302, 'Witaminy i minerały 100%, 120 tabletek', 'Aliness', null],
  [303, 'Naturalna Witamina E, 100 kapsułek', 'MedicaLine', null],
  [304, 'Żelazo organiczne MicroFerr® 25 mg, 100 tabletek VEGE', 'Aliness', null],
  [305, 'Maślan Sodu 550 mg (Kwas masłowy 170 mg), 100 VEGE kapsułek', 'MedicaLine', null],
  [306, 'Enzyme Complex PRO, 90 VEGE kapsułek', 'MedicaLine', null],
  [307, 'Dzikie oregano, olej 100%, 90 kapsułek miękkich', 'Aliness', null],
  [308, 'Ekstrakt z nasion ostropestu 190 mg + karczoch, 100 VEGE kapsułek', 'Aliness', null],
  [309, 'Olej z nasion czarnuszki 2% 500 mg, 120 kapsułek', 'Aliness', null],
  [310, 'Witamina C 1000 Buforowana Plus Proszek 250 g', 'MedicaLine', null],
  [311, 'Dzikie oregano 100% naturalny olej, 90% Naturalnego karwakrolu 30 ml', 'Avitale', null],
  [312, 'Chelato Magnez Medica 560 mg + wit. B6, 30 kapsułek', 'MedicaLine', null],
  [313, 'Seledrop - selen 110 mcg selenian (IV) sodu 30ml', 'Aura Herbals', null],
  [314, 'Witamina ADEK, krople 30 ml', 'Aura Herbals', null],
  [315, 'Witamina D3 Forte, krople 30 ml', 'Aura Herbals', null],
  [316, 'Witamina D3 (2000IU) + K2mk7, krople 30 ml', 'Aura Herbals', null],
  [317, 'Witamina K2mk7 - krople 30ml', 'Aura Herbals', null],
  [318, 'Olej lniany BOFLAX® do diety dr Budwig 500ml', 'IWNiRZ', null],
  [319, 'Naturalny olejek bergamotowy 9ml', 'Dr Beta', null],
  [320, 'Naturalny olejek cyprysowy 9ml', 'Dr Beta', null],
  [321, 'Naturalny olejek cytrynowy 9ml', 'Dr Beta', null],
  [322, 'Naturalny olejek z drzewa herbacianego 9ml', 'Dr Beta', null],
  [323, 'Naturalny olejek eukaliptusowy 9ml', 'Dr Beta', null],
  [324, 'Naturalny olejek geraniowy 9ml', 'Dr Beta', null],
  [325, 'Naturalny olejek grejfrutowy 9ml', 'Dr Beta', null],
  [326, 'Naturalny olejek jodłowy (pichtowy) 9ml', 'Dr Beta', null],
  [327, 'Naturalny olejek lawendowy 9ml', 'Dr Beta', null],
  [328, 'Naturalny olejek majerankowy 9ml', 'Dr Beta', null],
  [329, 'Naturalny olejek mandarynkowy 9ml', 'Dr Beta', null],
  [330, 'Naturalny olejek pomarańczowy 9ml', 'Dr Beta', null],
  [331, 'Naturalny olejek rozmarynowy 9ml', 'Dr Beta', null],
  [332, 'Naturalny olejek sosnowy 9ml', 'Dr Beta', null],
  [333, 'Naturalny olejek ylangowy 9ml', 'Dr Beta', null],
  [334, 'Vapomix ch-4 dla dzieci 9ml', 'Dr Beta', null],
  [335, 'Vapomix r-6 na stres 9ml', 'Dr Beta', null]
];

export const createProductQueryResults = (): ProductQueryResult[] => {
  return productQueryResultDbMocks.map(
    (productQueryResultDbMock: ProductQueryResultDbMock): ProductQueryResult => ({
      id: productQueryResultDbMock[0],
      manufacturerName: productQueryResultDbMock[2],
      name: productQueryResultDbMock[1]
    })
  );
};
